# name: Deploy Blog

# # 触发条件：在 push 到 master 分支后
# on:
#   push:
#     branches:
#       - master

# # 任务
# jobs:
#   build-and-deploy:
#     # 服务器环境：最新版 Ubuntu
#     runs-on: macOS-latest
#     steps:
#       # 拉取代码
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false

#       # 生成静态文件
#       - name: Build
#         env:
#           # VALINE_APPID: ${{ secrets.VALINE_APPID }}
#           # VALINE_APPKEY: ${{ secrets.VALINE_APPKEY }}
#           VSSUE_CLIENTID: ${{secrets.VSSUE_CLIENTID}}
#           VUSSE_CLIENTSECRET: ${{secrets.VUSSE_CLIENTSECRET}}
#           GA: ${{ secrets.GA }}
#         run: yarn install && yarn docs:build

#       # 部署到 GitHub Pages
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: docs/.vuepress/dist

name: Deploy Blog

on:
  push:
    branches:
      - master

jobs: # 工作流
  build-and-deploy: # 自定义名称
    runs-on: macOS-latest #虚拟机环境

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@master # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: run deploy.sh # 步骤3
        env: # 设置环境变量
          VSSUE_CLIENTID: ${{ secrets.VSSUE_CLIENTID }}
          VSSUE_CLIENTSECRET: ${{ secrets.VSSUE_CLIENTSECRET }}
          VALINE_APPID: ${{ secrets.VALINE_APPID }}
          VALINE_APPKEY: ${{ secrets.VALINE_APPKEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_EMAIL: ${{ secrets.ACCESS_EMAIL }}
          GOOGLE_SERACH: ${{ secrets.GOOGLE_SERACH }}
        run: yarn deploy
